//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace compWpf
{
    using System;
    using System.Collections.Generic;
    
    public partial class дистанции
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public дистанции()
        {
            this.этапы = new HashSet<этапы>();
            this.экипажи = new HashSet<экипажи>();
        }
    
        public System.Guid дистанция { get; set; }
        public System.Guid вид { get; set; }
        public string наимен { get; set; }
        public int порядок { get; set; }
        public Nullable<System.Guid> слет { get; set; }
    
        public virtual виды виды { get; set; }
        public virtual слеты слеты { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<этапы> этапы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<экипажи> экипажи { get; set; }
    }
}
