//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace compWpf
{
    using System;
    using System.Collections.Generic;
    
    public partial class туристы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public туристы()
        {
            this.экипажи = new HashSet<экипажи>();
        }
    
        public System.Guid слет { get; set; }
        public System.Guid школа { get; set; }
        public System.Guid турист { get; set; }
        public string фамилия { get; set; }
        public string имя { get; set; }
        public bool муж { get; set; }
        public bool младший { get; set; }
        public string прим { get; set; }
    
        public virtual слеты слеты { get; set; }
        public virtual школы школы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<экипажи> экипажи { get; set; }
    }
}
