//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace compWpf
{
    using System;
    using System.Collections.Generic;
    
    public partial class штрафы
    {
        public System.Guid штраф { get; set; }
        public System.Guid результат { get; set; }
        public int секунд { get; set; }
        public string прим { get; set; }
        public System.Guid этап { get; set; }
    
        public virtual этапы этапы { get; set; }
        public virtual результаты результаты { get; set; }
    }
}
