//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace compWpf
{
    using System;
    using System.Collections.Generic;
    
    public partial class экипажи
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public экипажи()
        {
            this.туристы = new HashSet<туристы>();
            this.результаты = new HashSet<результаты>();
        }
    
        public System.Guid дистанция { get; set; }
        public System.Guid экипаж { get; set; }
        public System.Guid судно { get; set; }
        public string прим { get; set; }
        public System.Guid школа { get; set; }
        public int номер { get; set; }
        public int место { get; set; }
        public int итог { get; set; }
    
        public virtual дистанции дистанции { get; set; }
        public virtual школы школы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<туристы> туристы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<результаты> результаты { get; set; }
        public virtual суда суда { get; set; }
    }
}
