//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace compWpf
{
    using System;
    using System.Collections.Generic;
    
    public partial class этапы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public этапы()
        {
            this.штрафы = new HashSet<штрафы>();
        }
    
        public System.Guid этап { get; set; }
        public System.Guid дистанция { get; set; }
        public string наимен { get; set; }
        public string судья { get; set; }
        public int порядок { get; set; }
    
        public virtual дистанции дистанции { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<штрафы> штрафы { get; set; }
    }
}
